In [1]:
# ! pip install
import pandas as pd
import numpy as np
# import kaggle
import os
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [3]:
!mkdir -p ~/.kaggle
!cp '/content/drive/My Drive/kaggle/kaggle.json' ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
import kaggle
kaggle.api.dataset_download_files('miguelroca/global-health-nutrition-mortality-economic-data', path='./data', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/miguelroca/global-health-nutrition-mortality-economic-data

In [5]:
df = pd.read_csv('./data/UnifiedDataset.csv')
df.head()

,Country,Year,Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,...,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
0,Afghanistan,1990,Both sexes,50.331,120.4,111.2,130.9,177.7,162.5,194.3,...,NaN,103.0,NaN,201.0,1195.0,174.0,67.80,197.08,435.60,1613.52
1,Afghanistan,1990,Female,51.442,114.2,105.1,124.7,173.1,158.0,189.7,...,NaN,103.0,NaN,201.0,1195.0,174.0,67.80,197.08,435.60,1613.52
2,Afghanistan,1990,Male,49.281,126.2,116.4,137.5,182.0,166.6,199.3,...,NaN,103.0,NaN,201.0,1195.0,174.0,67.80,197.08,435.60,1613.52
3,Afghanistan,1991,Both sexes,50.999,116.8,108.2,126.2,171.7,157.6,186.9,...,NaN,94.0,NaN,164.0,1043.0,159.0,64.96,173.68,370.08,1435.28
4,Afghanistan,1991,Female,52.119,110.7,102.1,120.4,167.1,153.0,182.6,...,NaN,94.0,NaN,164.0,1043.0,159.0,64.96,173.68,370.08,1435.28

In [6]:
df_important_years = df[(df['Year'] >= 2017) & (df['Year'] <= 2024)]
display(df_important_years.head())
display(df_important_years.iloc[:, 140:150])

,Country,Year,Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,...,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
81,Afghanistan,2017,Both sexes,64.130,49.61,42.08,57.23,64.94,53.74,76.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Afghanistan,2017,Female,65.656,46.12,38.95,53.20,61.25,50.50,72.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Afghanistan,2017,Male,62.701,52.95,44.77,61.25,68.49,56.62,81.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Afghanistan,2018,Both sexes,64.486,48.04,39.94,56.32,62.54,50.64,75.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Afghanistan,2018,Female,66.026,44.56,36.88,52.43,58.84,47.51,71.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
22045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
for i in range(15):
    display(df_important_years.iloc[:,i*10:(i+1)*10].describe())

,Year,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate
count,2205.000000,2205.000000,1452.000000,1452.000000,1452.000000,1452.000000,1452.000000,1452.000000
mean,2018.000000,73.036066,21.494153,16.339656,28.710234,28.639683,20.940585,40.228161
std,0.816682,7.700011,20.491962,15.570557,28.844768,30.133829,21.770108,45.434250
min,2017.000000,49.837000,1.420000,0.780000,1.780000,1.680000,0.850000,2.220000
25%,2017.000000,67.826000,5.330000,4.340000,5.940000,6.290000,5.057500,6.920000
50%,2018.000000,74.350000,13.555000,10.350000,17.790000,15.775000,12.175000,20.765000
75%,2019.000000,79.009000,32.022500,24.537500,43.697500,42.790000,30.212500,60.422500
max,2019.000000,87.747000,92.130000,81.020000,150.500000,130.800000,107.200000,248.300000

,% Death Cardiovascular,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular,Suicides Rate,Alcohol Abuse,Air Pollution Death Rate Stroke,Low CI Value Air Pollution Death Rate Stroke,High CI Value Air Pollution Death Rate Stroke,Air Pollution Death Rate Stroke Age Standarized,Low CI Value Air Pollution Death Rate Stroke Age Standarized
count,1620.000000,1620.000000,1620.000000,0.0,540.000000,0.0,0.0,0.0,0.0,0.0
mean,20.136049,13.849259,27.590309,NaN,6.096009,NaN,NaN,NaN,NaN,NaN
std,8.558476,5.735662,12.120369,NaN,5.424767,NaN,NaN,NaN,NaN,NaN
min,4.400000,3.200000,6.000000,NaN,0.000600,NaN,NaN,NaN,NaN,NaN
25%,13.600000,9.900000,17.975000,NaN,1.740000,NaN,NaN,NaN,NaN,NaN
50%,19.650000,12.900000,27.500000,NaN,4.460000,NaN,NaN,NaN,NaN,NaN
75%,24.600000,16.800000,35.100000,NaN,9.345000,NaN,NaN,NaN,NaN,NaN
max,58.700000,42.200000,73.800000,NaN,31.960000,NaN,NaN,NaN,NaN,NaN

,High CI Value Air Pollution Death Rate Stroke Age Standarized,Air Pollution Death Rate Ischaemic Heart Disease,Low CI Value Air Pollution Death Rate Ischaemic Heart Disease,High CI Value Air Pollution Death Rate Ischaemic Heart Disease,Air Pollution Death Rate Ischaemic Heart Disease Age Standarized,Low CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized,High CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized,Air Pollution Death Rate Lower Respiratory Infections,Low CI Value Air Pollution Death Rate Lower Respiratory Infections,High CI Value Air Pollution Death Rate Lower Respiratory Infections
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Air Pollution Death Rate Lower Respiratory Infections Age Standarized,Low CI Value Air Pollution Death Rate Lower Respiratory Infections Age Standarized,High CI Value Air Pollution Death Rate Lower Respiratory Infections Age Standarized,Air Pollution Death Rate Chronic Obstructive Pulmonary Disease,Low CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease,High CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease,Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized,Low CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized,High CI Value Air Pollution Death Rate Chronic Obstructive Pulmonary Disease Age Standarized,Air Pollution Death Rate Total
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Low CI Value Air Pollution Death Rate Total,High CI Value Air Pollution Death Rate Total,Air Pollution Death Rate Total Age Standarized,Low CI Value Air Pollution Death Rate Total Age Standarized,High CI Value Air Pollution Death Rate Total Age Standarized,Air Pollution Death Rate Trachea Bronchus Lung Cancers,Low CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers,High CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers,Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized,Low CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,High CI Value Air Pollution Death Rate Trachea Bronchus Lung Cancers Age Standarized,Unsafe Wash Mortality Rate,Poisoning Mortality Rate,Tobacco Prevalence,% Population Aged 0-14,% Population Aged 15-64,% Population Aged 65+,% Population Aged 65-69,% Population Aged 70-74,% Population Aged 75-79
count,0.0,0.0,0.0,862.000000,1662.000000,1662.000000,1662.000000,1110.000000,1110.000000,1110.000000
mean,NaN,NaN,NaN,21.981903,27.625908,63.486201,8.887891,3.035164,2.238915,1.609655
std,NaN,NaN,NaN,14.295785,10.482824,6.393646,6.416578,1.819144,1.556631,1.238472
min,NaN,NaN,NaN,0.000000,9.087558,46.766069,0.990269,0.429004,0.226945,0.066610
25%,NaN,NaN,NaN,10.700000,17.802230,59.289567,3.439864,1.416055,0.939556,0.593805
50%,NaN,NaN,NaN,21.300000,26.397049,64.764800,6.537128,2.469363,1.697664,1.171611
75%,NaN,NaN,NaN,30.200000,37.110301,67.453715,14.043655,4.725126,3.448473,2.463538
max,NaN,NaN,NaN,70.700000,50.770414,89.810795,30.878968,7.431046,7.348951,5.801685

,% Population Aged 80+,Maternal Mortality Ratio,Low CI Value Maternal Mortality Ratio,High CI Value Maternal Mortality Ratio,% of Births Attended By Skilled Personal,Neonatal Mortality Rate,Low CI Value Neonatal Mortality Rate,High CI Value Neonatal Mortality Rate,Incidence of Malaria,Incidence of Tuberculosis
count,1110.000000,537.000000,537.000000,537.000000,422.000000,1635.000000,1635.000000,1635.000000,630.000000,1644.000000
mean,1.986617,162.541899,113.882682,239.312849,91.867097,12.950648,9.147211,18.741284,87.577819,109.676484
std,2.006134,235.127789,163.756278,353.251806,14.116238,10.722487,7.481763,17.282184,131.306169,143.754280
min,0.083522,2.000000,1.000000,2.000000,41.600000,0.780000,0.270000,0.910000,0.000000,0.000000
25%,0.454428,12.000000,9.000000,17.000000,93.225000,3.700000,3.070000,4.360000,0.060000,12.000000
50%,1.207556,53.000000,36.000000,76.000000,98.400000,9.760000,6.650000,13.300000,5.480000,46.000000
75%,2.977366,213.000000,144.000000,318.000000,99.775000,20.600000,13.990000,29.640000,164.300000,156.000000
max,10.867064,1150.000000,847.000000,1710.000000,100.000000,43.650000,37.890000,88.780000,538.300000,918.000000

,Low CI Value Incidence of Tuberculosis,High CI Value Incidence of Tuberculosis,Hepatitis B Surface Antigen,Low CI Value Hepatitis B Surface Antigen,High CI Value Hepatitis B Surface Antigen,Intervention Against NTDs,Road Traffic Deaths,Reproductive Age Women,Adolescent Birth Rate,Universal Heath Care Coverage
count,1644.000000,1644.000000,0.0,0.0,0.0,1.096000e+03,0.0,30.000000,346.000000,537.000000
mean,76.086612,150.199720,NaN,NaN,NaN,9.600276e+06,NaN,48.950000,28.500289,63.949721
std,97.426283,203.053869,NaN,NaN,NaN,5.316310e+07,NaN,13.127012,27.968404,15.652335
min,0.000000,0.000000,NaN,NaN,NaN,0.000000e+00,NaN,26.300000,1.000000,25.000000
25%,9.875000,14.000000,NaN,NaN,NaN,1.500000e+01,NaN,44.000000,8.125000,48.000000
50%,35.000000,56.500000,NaN,NaN,NaN,8.304200e+04,NaN,45.800000,18.900000,69.000000
75%,112.000000,215.000000,NaN,NaN,NaN,5.021586e+06,NaN,56.100000,43.400000,76.000000
max,703.000000,1160.000000,NaN,NaN,NaN,6.970000e+08,NaN,77.900000,164.000000,89.000000

,Population 10 Percentage SDG Total,Population 10 Percentage SDG Urban,Population 10 Percentage SDG Rural,Population 25 Percentage SDG Total,Population 25 Percentage SDG Urban,Population 25 Percentage SDG Rural,Doctors,Nurses and Midwifes,Dentists,Pharmacists
count,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,475.000000,714.000000,503.000000,366.000000
mean,4.780000,5.130000,3.800000,0.69600,0.716000,0.742000,20.739347,49.167957,3.698942,4.741770
std,3.259478,3.509249,2.156932,0.34688,0.305843,0.438979,17.485111,124.299087,3.884935,4.037529
min,1.790000,1.960000,1.700000,0.41000,0.460000,0.280000,0.300000,0.097000,0.003000,0.039000
25%,2.220000,2.410000,2.070000,0.41000,0.490000,0.390000,5.810000,11.700000,0.485000,0.820000
50%,2.710000,2.820000,2.580000,0.51000,0.580000,0.540000,19.800000,26.455000,2.220000,4.190000
75%,7.970000,8.500000,6.140000,0.88000,0.790000,1.200000,32.670000,60.610000,6.385000,7.590000
max,9.210000,9.960000,6.510000,1.27000,1.260000,1.300000,84.220000,1853.000000,20.020000,19.070000

,Basic Drinking Water Services,Basic Sanization Services Total,Basic Sanization Services Urban,Basic Sanization Services Rural,Safely Sanitation Total,Safely Sanitation Urban,Safely Sanitation Rural,Basic Hand Washing Total,Basic Hand Washing Urban,Basic Hand Washing Rural
count,540.000000,537.000000,477.000000,469.000000,250.000000,207.000000,128.000000,226.000000,220.000000,223.000000
mean,82.060037,75.216182,78.703417,66.738273,68.703560,65.747391,59.213047,48.845973,56.722318,40.957848
std,21.671117,28.794034,24.761768,32.894577,28.297491,29.973113,31.965796,31.326605,29.869161,30.940902
min,22.830000,7.320000,17.770000,1.890000,6.320000,4.180000,3.810000,1.190000,1.760000,0.600000
25%,69.002500,51.470000,60.140000,37.050000,44.340000,39.790000,25.540000,19.817500,28.360000,12.520000
50%,91.310000,88.500000,91.740000,78.590000,77.935000,72.890000,61.700000,47.780000,58.930000,36.580000
75%,99.550000,98.170000,98.380000,97.790000,94.460000,94.200000,91.750000,79.290000,84.700000,71.890000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

,Clean Fuel and Technology,Birth Rate,Battle Related Deaths,% Injury Deaths,Death Rate,GDP per Capita,% Population $1.90 a day,% Population $3.20 a day,% Population $5.50 a day,Income per Capita
count,1072.000000,1130.000000,315.000000,536.000000,1130.000000,1610.000000,283.000000,283.000000,283.000000,1001.000000
mean,63.298507,20.283437,1624.352381,8.676234,7.721246,15279.160627,5.378092,11.283039,22.162191,11182.637097
std,36.326207,9.966152,4859.171574,3.757226,2.661727,21701.622482,11.528827,19.208018,25.622721,15047.620338
min,5.000000,5.900000,0.000000,2.374387,1.169000,261.247473,0.000000,0.000000,0.100000,205.600481
25%,28.000000,10.953000,43.000000,5.709043,5.845000,2027.777979,0.200000,0.400000,3.000000,1461.737353
50%,84.000000,18.077500,184.000000,8.723469,7.293000,6108.510696,1.000000,3.700000,12.800000,4204.953593
75%,95.000000,28.720750,666.000000,10.626832,9.255000,17850.933648,3.600000,9.900000,28.200000,13472.342638
max,95.000000,46.540000,29940.000000,19.492710,15.500000,185829.017960,51.800000,76.800000,92.700000,66019.072943

,Total Population,GNI per Capita,Conflict and Terrorism Deaths,Homicide Rate,Government Expenditure Education,Government Expenditure Military,Government Expenditure Health,Diet Composition Alcoholic Beverages,Diet Composition Other,Diet Composition Sugar
count,1.719000e+03,1575.000000,0.0,583.000000,538.000000,1308.000000,0.0,0.0,0.0,0.0
mean,8.247633e+07,13804.435429,NaN,7.006638,15.420540,6.325291,NaN,NaN,NaN,NaN
std,5.671440e+08,18550.262068,NaN,9.316195,5.077722,5.056260,NaN,NaN,NaN,NaN
min,1.137000e+04,280.000000,NaN,0.463616,0.875440,0.000000,NaN,NaN,NaN,NaN
25%,2.082958e+06,2020.000000,NaN,1.512904,11.835470,3.031688,NaN,NaN,NaN,NaN
50%,9.053300e+06,5520.000000,NaN,3.658229,15.257620,4.932971,NaN,NaN,NaN,NaN
75%,2.912147e+07,16600.000000,NaN,7.696473,18.598169,8.460873,NaN,NaN,NaN,NaN
max,7.673534e+09,117730.000000,NaN,56.690196,33.859089,31.991636,NaN,NaN,NaN,NaN

,Diet Composition Oils And Fats,Diet Composition Meat,Diet Composition Dairy And Eggs,Diet Composition Fruit And Vegetables,Diet Composition Starchy Roots,Diet Composition Pulses,Diet Composition Cereals And Grains,Vegetable Consumption,Fruit Consumption Plantains,Fruit Consumption Other
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,512.000000,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.702363,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.471076,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.280000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.360000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.925000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.440000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,377.170000,NaN,NaN

,Fruit Consumption Bananas,Fruit Consumption Dates,Fruit Consumption Other Citrus,Fruit Consumption Oranges And Mandarines,Fruit Consumption Apples,Fruit Consumption Lemons And Limes,Fruit Consumption Grapes,Fruit Consumption Grapefruit,Fruit Consumption Pineapples,Cereal Consumption Oats
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
vector = list(range(3,126))

df_important = df_important_years.drop(df.columns[vector], axis=1)
display(df_important)

,Country,Year,Gender,Diet Composition Cereals And Grains,Vegetable Consumption,Fruit Consumption Plantains,Fruit Consumption Other,Fruit Consumption Bananas,Fruit Consumption Dates,Fruit Consumption Other Citrus,...,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
81,Afghanistan,2017,Both sexes,NaN,48.34,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Afghanistan,2017,Female,NaN,48.34,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,Afghanistan,2017,Male,NaN,48.34,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,Afghanistan,2018,Both sexes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Afghanistan,2018,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22045,Zimbabwe,2018,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22046,Zimbabwe,2018,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22047,Zimbabwe,2019,Both sexes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22048,Zimbabwe,2019,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22049,Zimbabwe,2019,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
display(df_important.iloc[:,0:13].describe())
display(df_important.iloc[:,14:27].describe())

df_ramas = df_important.dropna(axis=1, how='all')
display(df_ramas)

,Year,Diet Composition Cereals And Grains,Vegetable Consumption,Fruit Consumption Plantains,Fruit Consumption Other,Fruit Consumption Bananas,Fruit Consumption Dates,Fruit Consumption Other Citrus,Fruit Consumption Oranges And Mandarines,Fruit Consumption Apples,Fruit Consumption Lemons And Limes
count,2205.000000,0.0,512.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2018.000000,NaN,90.702363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.816682,NaN,68.471076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2017.000000,NaN,6.280000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2017.000000,NaN,41.360000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.000000,NaN,72.925000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2019.000000,NaN,116.440000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2019.000000,NaN,377.170000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Fruit Consumption Grapefruit,Fruit Consumption Pineapples,Cereal Consumption Oats,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

           Country  Year      Gender  Vegetable Consumption
81     Afghanistan  2017  Both sexes                  48.34
82     Afghanistan  2017      Female                  48.34
83     Afghanistan  2017        Male                  48.34
84     Afghanistan  2018  Both sexes                    NaN
85     Afghanistan  2018      Female                    NaN
...            ...   ...         ...                    ...
22045     Zimbabwe  2018      Female                    NaN
22046     Zimbabwe  2018        Male                    NaN
22047     Zimbabwe  2019  Both sexes                    NaN
22048     Zimbabwe  2019      Female                    NaN
22049     Zimbabwe  2019        Male                    NaN

[2205 rows x 4 columns]

In [10]:
kaggle.api.dataset_download_files('ghaithmechi/food-prices-for-nutrition', path='./data', unzip=True)
kaggle.api.dataset_download_files('mjshri23/life-expectancy-and-socio-economic-world-bank', path='./data', unzip=True)
kaggle.api.dataset_download_files('scibearia/meat-consumption-per-capita', path='./data', unzip=True)
kaggle.api.dataset_download_files('ibrahimshahrukh/global-price-of-healthy-diet-dataset', path='./data', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/ghaithmechi/food-prices-for-nutrition
Dataset URL: https://www.kaggle.com/datasets/mjshri23/life-expectancy-and-socio-economic-world-bank
Dataset URL: https://www.kaggle.com/datasets/scibearia/meat-consumption-per-capita
Dataset URL: https://www.kaggle.com/datasets/ibrahimshahrukh/global-price-of-healthy-diet-dataset

In [11]:
df_food_prices = pd.read_csv('./data/2bca3f30-534f-4246-a0ad-15f6e16018bb_Data.csv', encoding='latin-1')
df_life_expectancies = pd.read_csv('./data/life expectancy.csv')
df_meat_consumption = pd.read_csv('./data/Consumption of meat per capita.csv')
df_global_price = pd.read_csv('./data/price_of_healthy_diet_clean.csv')

In [12]:
display(df_food_prices.columns)
display(df_food_prices.head())
print("\n\n\n")

display(df_life_expectancies.columns)
display(df_life_expectancies.head())
print("\n\n\n")

display(df_meat_consumption.columns)
display(df_meat_consumption.head())

Index(['Classification Name', 'Classification Code', 'Country Name',
       'Country Code', 'Time', 'Time Code',
       'Cost of an energy sufficient diet [CoCA]',
       'Cost of a nutrient adequate diet [CoNA]',
       'Cost of a healthy diet [CoHD]',
       'Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA]',
       'Cost of fruits [CoHD_f]', 'Cost of vegetables [CoHD_v]',
       'Cost of starchy staples [CoHD_ss]',
       'Cost of animal-source foods [CoHD_asf]',
       'Cost of legumes, nuts and seeds [CoHD_lns]',
       'Cost of oils and fats [CoHD_of]',
       'Cost share for fruits in a least-cost healthy diet [CoHD_f_prop]',
       'Cost share for vegetables in a least-cost healthy diet [CoHD_v_prop]',
       'Cost share for starchy staples in a least-cost healthy diet [CoHD_ss_prop]',
       'Cost share for animal-sourced foods in a least-cost healthy diet [CoHD_asf_prop]',
       'Cost share for legumes, nuts and seeds in a least-cost healthy diet [CoHD_lns_prop]',
       'Cost share for oils and fats in a least-cost healthy diet [CoHD_of_prop]',
       'Cost of fruits relative to the starchy staples in a least-cost healthy diet [CoHD_f_ss]',
       'Cost of vegetables relative to the starchy staples in a least-cost healthy diet [CoHD_v_ss]',
       'Cost of animal-sourced foods relative to the starchy staples in a least-cost healthy diet [CoHD_asf_ss]',
       'Cost of legumes, nuts and seeds relative to the starchy staples in a least-cost healthy diet [CoHD_lns_ss]',
       'Cost of oils and fats relative to the starchy staples in a least-cost healthy diet [CoHD_of_ss]',
       'Affordability of an energy sufficient diet: ratio of cost to the food poverty line [CoCA_pov]',
       'Affordability of a nutrient adequate diet: ratio of cost to the food poverty line [CoNA_pov]',
       'Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]',
       'Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp]',
       'Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp]',
       'Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp]',
       'Percent of the population who cannot afford sufficient calories [CoCA_headcount]',
       'Percent of the population who cannot afford nutrient adequacy [CoNA_headcount]',
       'Percent of the population who cannot afford a healthy diet [CoHD_headcount]',
       'Millions of people who cannot afford sufficient calories [CoCA_unafford_n]',
       'Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n]',
       'Millions of people who cannot afford a healthy diet [CoHD_unafford_n]',
       'Population [Pop]'],
      dtype='object')

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

Index(['Country Name', 'Country Code', 'Region', 'IncomeGroup', 'Year',
       'Life Expectancy World Bank', 'Prevelance of Undernourishment', 'CO2',
       'Health Expenditure %', 'Education Expenditure %', 'Unemployment',
       'Corruption', 'Sanitation', 'Injuries', 'Communicable',
       'NonCommunicable'],
      dtype='object')

,Country Name,Country Code,Region,IncomeGroup,Year,Life Expectancy World Bank,Prevelance of Undernourishment,CO2,Health Expenditure %,Education Expenditure %,Unemployment,Corruption,Sanitation,Injuries,Communicable,NonCommunicable
0,Afghanistan,AFG,South Asia,Low income,2001,56.308,47.8,730.0,NaN,NaN,10.809000,NaN,NaN,2179727.10,9689193.70,5795426.38
1,Angola,AGO,Sub-Saharan Africa,Lower middle income,2001,47.059,67.5,15960.0,4.483516,NaN,4.004000,NaN,NaN,1392080.71,11190210.53,2663516.34
2,Albania,ALB,Europe & Central Asia,Upper middle income,2001,74.288,4.9,3230.0,7.139524,3.4587,18.575001,NaN,40.520895,117081.67,140894.78,532324.75
3,Andorra,AND,Europe & Central Asia,High income,2001,NaN,NaN,520.0,5.865939,NaN,NaN,NaN,21.788660,1697.99,695.56,13636.64
4,United Arab Emirates,ARE,Middle East & North Africa,High income,2001,74.544,2.8,97200.0,2.484370,NaN,2.493000,NaN,NaN,144678.14,65271.91,481740.70

Index(['Entity', 'Year', 'Poultry', 'Beef', 'Sheep and goat', 'Pork',
       'Other meats', 'Fish and seafood'],
      dtype='object')

,Entity,Year,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood
0,Afghanistan,1961,0.641744,4.889479,8.332486,NaN,0.865845,0.030559
1,Afghanistan,1962,0.672726,5.106605,8.072717,NaN,0.896969,0.030578
2,Afghanistan,1963,0.673156,5.160862,8.251259,NaN,1.091328,0.030598
3,Afghanistan,1964,0.683714,5.132955,8.520909,NaN,1.030673,0.030614
4,Afghanistan,1965,0.714625,5.094256,8.820517,NaN,1.082147,0.030627

In [13]:
column_number = list(range(2))
column_number += [3, 5]
print(column_number)

print(df_food_prices.columns[column_number])

df_food_prices = df_food_prices.drop(columns=df_food_prices.columns[column_number])

[0, 1, 3, 5]
Index(['Classification Name', 'Classification Code', 'Country Code',
       'Time Code'],
      dtype='object')

In [14]:
df_meat_consumption = df_meat_consumption[(df_meat_consumption['Year'] >= 2017) & (df_meat_consumption['Year'] <= 2019)]
display(df_meat_consumption.describe())

df_food_prices = df_food_prices[(df_food_prices['Time'] >= 2017) & (df_food_prices['Time'] <= 2019)]
df_food_prices = df_food_prices.replace('..', np.nan)

,Year,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood
count,548.000000,548.000000,548.000000,548.000000,537.000000,547.000000,548.000000
mean,2018.009124,21.537052,11.051582,2.919963,14.301117,1.425862,19.282810
std,0.819054,17.057418,9.165573,5.370029,15.403720,3.817196,16.730197
min,2017.000000,0.400000,0.190000,0.000000,0.000000,0.000000,0.380000
25%,2017.000000,7.267499,3.982496,0.520000,1.110000,0.090000,6.945004
50%,2018.000000,19.200001,8.124996,1.324989,8.610001,0.490000,14.764999
75%,2019.000000,31.666381,15.569961,3.337320,24.269997,1.355000,26.610000
max,2019.000000,80.416290,52.140010,64.329900,67.769780,45.489986,95.108190

In [15]:
display(df_food_prices)
display(df_food_prices.describe())

,Country Name,Time,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],Cost of fruits [CoHD_f],Cost of vegetables [CoHD_v],Cost of starchy staples [CoHD_ss],Cost of animal-source foods [CoHD_asf],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Tunisia,2017.0,0.604,1.88,3.476,5.75,1.127,0.527,0.318,0.841,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Tunisia,2018.0,NaN,NaN,3.559,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,21.2,NaN,NaN,2.5,11565203
2,Tunisia,2019.0,NaN,NaN,3.628,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,20.8,NaN,NaN,2.4,11694721
5,Algeria,2017.0,0.773,2.323,3.763,4.87,0.979,0.699,0.496,0.964,...,0.124,0.374,0.605,0.2,7.2,35.2,0.1,3,14.6,41389174
6,Algeria,2018.0,NaN,NaN,3.822,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.9,NaN,NaN,14.3,42228415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3711,West Bank and Gaza,2018.0,NaN,NaN,3.398,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.4,NaN,NaN,0.8,4569087
3712,West Bank and Gaza,2019.0,NaN,NaN,3.493,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18,NaN,NaN,0.8,4685306
3715,WORLD,2017.0,0.825,2.441,3.295,1.34985661614093,0.658,0.782,0.503,0.872,...,0.212,0.591,0.808,4.9,32,43.7,351.1,2293.8,3133.4,7262507298
3716,WORLD,2018.0,NaN,NaN,3.355,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,3032.7,7304447092
3717,WORLD,2019.0,NaN,NaN,3.431,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41.2,NaN,NaN,3003.6,7381667234

             Time
count  2232.00000
mean   2018.00000
std       0.81668
min    2017.00000
25%    2017.00000
50%    2018.00000
75%    2019.00000
max    2019.00000

In [16]:
df_food_prices = df_food_prices.dropna(axis=1, thresh=df_food_prices.shape[0] * 0.5)
for i in range(7):
    df_food_prices[df_food_prices.columns[i]] = pd.to_numeric(df_food_prices[df_food_prices.columns[i]], errors='ignore')
display(df_food_prices)
display(df_food_prices.dtypes)
display(df_food_prices.describe())

/tmp/ipykernel_34970/2138993049.py:3: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df_food_prices[df_food_prices.columns[i]] = pd.to_numeric(df_food_prices[df_food_prices.columns[i]], errors='ignore')

,Country Name,Time,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Tunisia,2017.0,3.476,3.511,21.8,2.5,1.143344e+07
1,Tunisia,2018.0,3.559,3.595,21.2,2.5,1.156520e+07
2,Tunisia,2019.0,3.628,3.665,20.8,2.4,1.169472e+07
5,Algeria,2017.0,3.763,3.801,35.2,14.6,4.138917e+07
6,Algeria,2018.0,3.822,3.861,33.9,14.3,4.222842e+07
...,...,...,...,...,...,...,...
3711,West Bank and Gaza,2018.0,3.398,3.034,18.4,0.8,4.569087e+06
3712,West Bank and Gaza,2019.0,3.493,3.119,18.0,0.8,4.685306e+06
3715,WORLD,2017.0,3.295,2.942,43.7,3133.4,7.262507e+09
3716,WORLD,2018.0,3.355,2.996,42.0,3032.7,7.304447e+09
3717,WORLD,2019.0,3.431,3.064,41.2,3003.6,7.381667e+09

Country Name                                                                           object
Time                                                                                  float64
Cost of a healthy diet [CoHD]                                                         float64
Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]    float64
Percent of the population who cannot afford a healthy diet [CoHD_headcount]           float64
Millions of people who cannot afford a healthy diet [CoHD_unafford_n]                 float64
Population [Pop]                                                                      float64
dtype: object

,Time,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
count,2232.00000,2132.000000,2060.000000,1836.000000,1836.000000,2.144000e+03
mean,2018.00000,3.367530,3.101166,36.668464,79.231972,1.633245e+08
std,0.81668,0.662137,0.642592,34.277327,338.378152,6.753176e+08
min,2017.00000,1.822000,1.627000,0.000000,0.000000,2.956700e+04
25%,2017.00000,2.909000,2.652000,2.500000,0.200000,2.446644e+06
50%,2018.00000,3.300000,3.017000,22.400000,1.900000,1.002428e+07
75%,2019.00000,3.706000,3.449000,72.075000,16.900000,4.151540e+07
max,2019.00000,6.398000,6.463000,97.500000,3133.400000,7.381667e+09

In [17]:
df_life_expectancies = df_life_expectancies[(df_life_expectancies['Year'] >= 2017) & (df_life_expectancies['Year'] <= 2019)]
display(df_life_expectancies.describe())

,Year,Life Expectancy World Bank,Prevelance of Undernourishment,CO2,Health Expenditure %,Education Expenditure %,Unemployment,Corruption,Sanitation,Injuries,Communicable,NonCommunicable
count,522.00000,492.000000,414.000000,4.980000e+02,497.000000,394.000000,474.000000,186.000000,321.000000,5.220000e+02,5.220000e+02,5.220000e+02
mean,2018.00000,72.354110,9.152899,1.784687e+05,6.684682,4.617275,7.163829,2.817204,58.083757,1.275415e+06,3.691637e+06,8.257192e+06
std,0.81728,7.770382,10.230299,9.119127e+05,2.939202,2.081913,5.624183,0.646341,30.192485,4.913043e+06,1.357453e+07,3.258495e+07
min,2017.00000,52.240000,2.500000,1.000000e+01,1.525117,1.152660,0.100000,1.500000,6.074357,4.701200e+02,3.529400e+02,2.481820e+03
25%,2017.00000,66.660000,2.500000,2.700000e+03,4.436535,3.206437,3.533000,2.500000,30.486777,6.146649e+04,4.844668e+04,3.602466e+05
50%,2018.00000,74.105134,5.400000,1.339500e+04,6.460916,4.383355,5.349000,3.000000,60.090726,2.472707e+05,2.834696e+05,1.553275e+06
75%,2019.00000,78.106762,11.875000,6.500500e+04,8.442921,5.453787,8.870000,3.000000,86.178166,8.841015e+05,2.155027e+06,4.320482e+06
max,2019.00000,84.356341,58.900000,1.070722e+07,23.961813,15.750000,28.469999,4.500000,100.000004,5.356391e+07,1.519178e+08,3.246378e+08

In [18]:
display(df_important_years.columns[0:30])
display(df_important_years.describe())

df_important = df_important_years.iloc[:, 0:13]
display(df_important.head())
display(df_important.describe())

Index(['Country', 'Year', 'Gender', 'Life Expectancy', 'Infant Mortality Rate',
       'Low CI Value Infant Mortality Rate',
       'High CI Value Infant Mortality Rate', 'Under 5 Mortality Rate',
       'Low CI Value Under 5 Mortality Rate',
       'High CI Value Under 5 Mortality Rate', '% Death Cardiovascular',
       'Low CI Value % Death Cardiovascular',
       'High CI Value % Death Cardiovascular', 'Suicides Rate',
       'Alcohol Abuse', 'Air Pollution Death Rate Stroke',
       'Low CI Value Air Pollution Death Rate Stroke',
       'High CI Value Air Pollution Death Rate Stroke',
       'Air Pollution Death Rate Stroke Age Standarized',
       'Low CI Value Air Pollution Death Rate Stroke Age Standarized',
       'High CI Value Air Pollution Death Rate Stroke Age Standarized',
       'Air Pollution Death Rate Ischaemic Heart Disease',
       'Low CI Value Air Pollution Death Rate Ischaemic Heart Disease',
       'High CI Value Air Pollution Death Rate Ischaemic Heart Disease',
       'Air Pollution Death Rate Ischaemic Heart Disease Age Standarized',
       'Low CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized',
       'High CI Value Air Pollution Death Rate Ischaemic Heart Disease Age Standarized',
       'Air Pollution Death Rate Lower Respiratory Infections',
       'Low CI Value Air Pollution Death Rate Lower Respiratory Infections',
       'High CI Value Air Pollution Death Rate Lower Respiratory Infections'],
      dtype='object')

,Year,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,% Death Cardiovascular,Low CI Value % Death Cardiovascular,...,Cereal Consumption Rye,Cereal Consumption Barley,Cereal Consumption Sorghum,Cereal Consumption Maize,Cereal Consumption Wheat,Cereal Consumption Rice,Diet Calories Animal Protein,Diet Calories Plant Protein,Diet Calories Fat,Diet Calories Carbohydrates
count,2205.000000,2205.000000,1452.000000,1452.000000,1452.000000,1452.000000,1452.000000,1452.000000,1620.000000,1620.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2018.000000,73.036066,21.494153,16.339656,28.710234,28.639683,20.940585,40.228161,20.136049,13.849259,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.816682,7.700011,20.491962,15.570557,28.844768,30.133829,21.770108,45.434250,8.558476,5.735662,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2017.000000,49.837000,1.420000,0.780000,1.780000,1.680000,0.850000,2.220000,4.400000,3.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2017.000000,67.826000,5.330000,4.340000,5.940000,6.290000,5.057500,6.920000,13.600000,9.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.000000,74.350000,13.555000,10.350000,17.790000,15.775000,12.175000,20.765000,19.650000,12.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2019.000000,79.009000,32.022500,24.537500,43.697500,42.790000,30.212500,60.422500,24.600000,16.800000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2019.000000,87.747000,92.130000,81.020000,150.500000,130.800000,107.200000,248.300000,58.700000,42.200000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Country,Year,Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,% Death Cardiovascular,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular
81,Afghanistan,2017,Both sexes,64.130,49.61,42.08,57.23,64.94,53.74,76.83,35.5,21.7,50.4
82,Afghanistan,2017,Female,65.656,46.12,38.95,53.20,61.25,50.50,72.52,35.9,21.3,51.7
83,Afghanistan,2017,Male,62.701,52.95,44.77,61.25,68.49,56.62,81.18,35.0,22.0,49.1
84,Afghanistan,2018,Both sexes,64.486,48.04,39.94,56.32,62.54,50.64,75.41,35.4,21.7,50.1
85,Afghanistan,2018,Female,66.026,44.56,36.88,52.43,58.84,47.51,71.09,36.0,21.4,51.6

,Year,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,% Death Cardiovascular,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular
count,2205.000000,2205.000000,1452.000000,1452.000000,1452.000000,1452.000000,1452.000000,1452.000000,1620.000000,1620.000000,1620.000000
mean,2018.000000,73.036066,21.494153,16.339656,28.710234,28.639683,20.940585,40.228161,20.136049,13.849259,27.590309
std,0.816682,7.700011,20.491962,15.570557,28.844768,30.133829,21.770108,45.434250,8.558476,5.735662,12.120369
min,2017.000000,49.837000,1.420000,0.780000,1.780000,1.680000,0.850000,2.220000,4.400000,3.200000,6.000000
25%,2017.000000,67.826000,5.330000,4.340000,5.940000,6.290000,5.057500,6.920000,13.600000,9.900000,17.975000
50%,2018.000000,74.350000,13.555000,10.350000,17.790000,15.775000,12.175000,20.765000,19.650000,12.900000,27.500000
75%,2019.000000,79.009000,32.022500,24.537500,43.697500,42.790000,30.212500,60.422500,24.600000,16.800000,35.100000
max,2019.000000,87.747000,92.130000,81.020000,150.500000,130.800000,107.200000,248.300000,58.700000,42.200000,73.800000

In [19]:
display(df_global_price.head())
display(df_global_price.describe())

,country_code,country,region,year,cost_healthy_diet_ppp_usd,annual_cost_healthy_diet_usd,cost_vegetables_ppp_usd,cost_fruits_ppp_usd,total_food_components_cost,cost_category,data_quality
0,8,Albania,Africa,2017,3.04,1109.60,NaN,NaN,NaN,High Cost,Estimated value
1,8,Albania,Africa,2018,3.13,1142.45,NaN,NaN,NaN,High Cost,Estimated value
2,8,Albania,Africa,2019,3.32,1211.80,NaN,NaN,NaN,High Cost,Estimated value
3,8,Albania,Africa,2020,3.40,1241.00,NaN,NaN,NaN,High Cost,Estimated value
4,8,Albania,Africa,2021,3.49,1273.85,0.6,0.77,1.37,High Cost,Estimated value

,country_code,year,cost_healthy_diet_ppp_usd,annual_cost_healthy_diet_usd,cost_vegetables_ppp_usd,cost_fruits_ppp_usd,total_food_components_cost
count,1379.000000,1379.000000,1379.000000,1379.000000,166.000000,166.000000,166.000000
mean,420.996374,2020.490210,3.677411,1342.255076,0.762711,0.675361,1.438072
std,248.244476,2.293522,0.899691,328.387152,0.293952,0.299848,0.496151
min,8.000000,2017.000000,1.700000,620.500000,0.210000,0.170000,0.380000
25%,203.000000,2018.000000,3.010000,1098.650000,0.532500,0.450000,1.142500
50%,417.000000,2020.000000,3.550000,1295.750000,0.740000,0.660000,1.440000
75%,642.500000,2022.000000,4.205000,1534.825000,0.937500,0.827500,1.667500
max,894.000000,2024.000000,8.390000,3062.350000,1.690000,2.500000,3.400000

In [23]:
rename_table = {'Country Name': 'Country', 'Time': 'Year'}
#df_food_prices.rename(columns=rename_table, inplace=True)
display(df_food_prices)
print('\n\n\n')

# rename_table = {'country': 'Country', 'year': 'Year'}
# df_global_price = df_global_price.iloc[:, [1,3,4,5]]
# df_global_price.rename(columns=rename_table, inplace=True)
display(df_global_price)
print('\n\n\n')

display(df_life_expectancies)
print('\n\n\n')

# rename_table = {'Entity': 'Country'}
# df_meat_consumption.rename(columns=rename_table, inplace=True)
display(df_meat_consumption)
print('\n\n\n')

display(df_important)

,Country,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Tunisia,2017.0,3.476,3.511,21.8,2.5,1.143344e+07
1,Tunisia,2018.0,3.559,3.595,21.2,2.5,1.156520e+07
2,Tunisia,2019.0,3.628,3.665,20.8,2.4,1.169472e+07
5,Algeria,2017.0,3.763,3.801,35.2,14.6,4.138917e+07
6,Algeria,2018.0,3.822,3.861,33.9,14.3,4.222842e+07
...,...,...,...,...,...,...,...
3711,West Bank and Gaza,2018.0,3.398,3.034,18.4,0.8,4.569087e+06
3712,West Bank and Gaza,2019.0,3.493,3.119,18.0,0.8,4.685306e+06
3715,WORLD,2017.0,3.295,2.942,43.7,3133.4,7.262507e+09
3716,WORLD,2018.0,3.355,2.996,42.0,3032.7,7.304447e+09
3717,WORLD,2019.0,3.431,3.064,41.2,3003.6,7.381667e+09

       Country  Year  cost_healthy_diet_ppp_usd  annual_cost_healthy_diet_usd
0      Albania  2017                       3.04                       1109.60
1      Albania  2018                       3.13                       1142.45
2      Albania  2019                       3.32                       1211.80
3      Albania  2020                       3.40                       1241.00
4      Albania  2021                       3.49                       1273.85
...        ...   ...                        ...                           ...
1374    Zambia  2021                       3.28                       1197.20
1375    Zambia  2022                       3.61                       1317.65
1376    Zambia  2023                       3.81                       1390.65
1377    Zambia  2024                       3.99                       1456.35
1378  Zimbabwe  2017                       3.54                       1292.10

[1379 rows x 4 columns]

,Country Name,Country Code,Region,IncomeGroup,Year,Life Expectancy World Bank,Prevelance of Undernourishment,CO2,Health Expenditure %,Education Expenditure %,Unemployment,Corruption,Sanitation,Injuries,Communicable,NonCommunicable
2784,Afghanistan,AFG,South Asia,Low income,2017,64.130,23.0,4780.000210,12.620817,3.373310,11.180000,2.0,NaN,3469080.74,6301361.92,7307944.71
2785,Angola,AGO,Sub-Saharan Africa,Lower middle income,2017,60.379,15.4,24250.000000,2.791503,2.466879,7.408000,NaN,NaN,1155447.76,7697608.85,3949010.17
2786,Albania,ALB,Europe & Central Asia,Upper middle income,2017,78.333,4.7,5139.999866,5.012636,3.611730,13.620000,NaN,47.052290,81733.67,54297.20,619848.51
2787,Andorra,AND,Europe & Central Asia,High income,2017,NaN,NaN,469.999999,6.589455,3.217090,NaN,NaN,99.999999,2030.39,769.12,17980.89
2788,United Arab Emirates,ARE,Middle East & North Africa,High income,2017,77.647,6.4,197039.993286,4.059595,NaN,2.460000,NaN,95.877801,382300.29,120496.08,1502019.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3301,Vanuatu,VUT,East Asia & Pacific,Lower middle income,2019,70.474,12.4,209.999993,3.360347,1.777880,1.801000,3.0,NaN,12484.18,26032.56,69213.56
3302,Samoa,WSM,East Asia & Pacific,Lower middle income,2019,73.321,4.4,300.000012,6.363094,4.706250,8.406000,4.0,47.698788,6652.84,9095.19,43798.62
3303,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,2019,64.131,6.3,439640.014648,9.109355,5.917710,28.469999,NaN,NaN,3174676.10,13198944.71,10214261.89
3304,Zambia,ZMB,Sub-Saharan Africa,Low income,2019,63.886,NaN,6800.000191,5.312203,4.465180,12.520000,2.5,NaN,510982.75,4837094.00,2649687.82
3305,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,2019,61.490,NaN,11760.000229,7.703565,NaN,4.833000,2.5,25.963544,644798.93,4187087.31,2364031.48

,Country,Year,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood
56,Afghanistan,2017,1.790000,2.920000,4.450000,0.020000,0.330000,0.430000
57,Afghanistan,2018,1.460000,2.670000,4.319999,0.030000,0.320000,0.420000
58,Afghanistan,2019,1.810000,2.760000,3.450000,0.040000,0.310000,0.380000
117,Albania,2017,11.549996,13.879995,9.119997,8.259997,0.170000,8.749997
118,Albania,2018,9.509971,13.419958,10.929966,5.909981,0.000000,9.219972
...,...,...,...,...,...,...,...,...
10015,Zambia,2018,3.319999,11.649995,0.630000,1.789999,2.269999,13.029994
10016,Zambia,2019,2.720000,9.460001,0.540000,1.560000,2.190000,13.070002
10075,Zimbabwe,2017,5.090000,41.409996,1.810000,0.740000,2.500000,3.930000
10076,Zimbabwe,2018,4.379997,40.989970,1.819999,0.520000,2.389998,3.119998
10077,Zimbabwe,2019,4.470001,40.980010,1.770001,0.690000,2.370001,2.020001

,Country,Year,Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,% Death Cardiovascular,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular
81,Afghanistan,2017,Both sexes,64.130,49.61,42.08,57.23,64.94,53.74,76.83,35.5,21.7,50.4
82,Afghanistan,2017,Female,65.656,46.12,38.95,53.20,61.25,50.50,72.52,35.9,21.3,51.7
83,Afghanistan,2017,Male,62.701,52.95,44.77,61.25,68.49,56.62,81.18,35.0,22.0,49.1
84,Afghanistan,2018,Both sexes,64.486,48.04,39.94,56.32,62.54,50.64,75.41,35.4,21.7,50.1
85,Afghanistan,2018,Female,66.026,44.56,36.88,52.43,58.84,47.51,71.09,36.0,21.4,51.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22045,Zimbabwe,2018,Female,62.598,NaN,NaN,NaN,NaN,NaN,NaN,27.4,16.8,40.1
22046,Zimbabwe,2018,Male,59.501,NaN,NaN,NaN,NaN,NaN,NaN,30.3,19.8,43.0
22047,Zimbabwe,2019,Both sexes,61.490,NaN,NaN,NaN,NaN,NaN,NaN,28.4,17.8,41.1
22048,Zimbabwe,2019,Female,62.899,NaN,NaN,NaN,NaN,NaN,NaN,27.1,16.5,39.8
22049,Zimbabwe,2019,Male,59.798,NaN,NaN,NaN,NaN,NaN,NaN,30.3,19.7,43.0

In [25]:
df_merge_lifeexpectency_cost = df_food_prices.iloc[:,0:5]
df_merge_lifeexpectency_cost = df_merge_lifeexpectency_cost.merge(df_important, how="inner", on=['Country', 'Year'])
display(df_merge_lifeexpectency_cost)
df_merge_meat_lifeexpectency = df_merge_lifeexpectency_cost.merge(df_meat_consumption, how="inner", on=['Country', 'Year'])
display(df_merge_meat_lifeexpectency)
df_merge_total = df_merge_meat_lifeexpectency.merge(df_global_price, how="inner", on=['Country', 'Year'])
display(df_merge_total)
df_merge_total = df_merge_total.dropna(axis=1, thresh=df_merge_total.shape[0] * 0.5)
display(df_merge_total.describe())

,Country,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,High CI Value Under 5 Mortality Rate,% Death Cardiovascular,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular
0,Tunisia,2017.0,3.476,3.511,21.8,Both sexes,76.310,NaN,NaN,NaN,NaN,NaN,NaN,15.8,9.9,23.2
1,Tunisia,2017.0,3.476,3.511,21.8,Female,78.350,NaN,NaN,NaN,NaN,NaN,NaN,12.6,7.9,18.5
2,Tunisia,2017.0,3.476,3.511,21.8,Male,74.297,NaN,NaN,NaN,NaN,NaN,NaN,19.2,12.1,27.9
3,Tunisia,2018.0,3.559,3.595,21.2,Both sexes,76.505,NaN,NaN,NaN,NaN,NaN,NaN,15.8,9.9,23.3
4,Tunisia,2018.0,3.559,3.595,21.2,Female,78.536,NaN,NaN,NaN,NaN,NaN,NaN,12.5,7.9,18.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,Vietnam,2018.0,3.663,3.271,22.4,Female,79.442,NaN,NaN,NaN,NaN,NaN,NaN,13.9,8.6,20.5
5264,Vietnam,2018.0,3.663,3.271,22.4,Male,71.207,NaN,NaN,NaN,NaN,NaN,NaN,29.4,19.1,40.9
5265,Vietnam,2019.0,3.776,3.371,19.8,Both sexes,75.400,NaN,NaN,NaN,NaN,NaN,NaN,21.2,13.4,30.6
5266,Vietnam,2019.0,3.776,3.371,19.8,Female,79.523,NaN,NaN,NaN,NaN,NaN,NaN,13.7,8.4,20.4
5267,Vietnam,2019.0,3.776,3.371,19.8,Male,71.301,NaN,NaN,NaN,NaN,NaN,NaN,29.1,18.7,40.7

,Country,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,...,High CI Value Under 5 Mortality Rate,% Death Cardiovascular,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood
0,Tunisia,2017.0,3.476,3.511,21.8,Both sexes,76.310,NaN,NaN,NaN,...,NaN,15.8,9.9,23.2,16.480000,5.42,5.389999,0.000000,0.28,12.289999
1,Tunisia,2017.0,3.476,3.511,21.8,Female,78.350,NaN,NaN,NaN,...,NaN,12.6,7.9,18.5,16.480000,5.42,5.389999,0.000000,0.28,12.289999
2,Tunisia,2017.0,3.476,3.511,21.8,Male,74.297,NaN,NaN,NaN,...,NaN,19.2,12.1,27.9,16.480000,5.42,5.389999,0.000000,0.28,12.289999
3,Tunisia,2018.0,3.559,3.595,21.2,Both sexes,76.505,NaN,NaN,NaN,...,NaN,15.8,9.9,23.3,16.810000,5.17,5.380000,NaN,0.27,12.520000
4,Tunisia,2018.0,3.559,3.595,21.2,Female,78.536,NaN,NaN,NaN,...,NaN,12.5,7.9,18.5,16.810000,5.17,5.380000,NaN,0.27,12.520000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4939,Vietnam,2018.0,3.663,3.271,22.4,Female,79.442,NaN,NaN,NaN,...,NaN,13.9,8.6,20.5,11.310000,3.03,0.210000,29.630000,0.01,39.220000
4940,Vietnam,2018.0,3.663,3.271,22.4,Male,71.207,NaN,NaN,NaN,...,NaN,29.4,19.1,40.9,11.310000,3.03,0.210000,29.630000,0.01,39.220000
4941,Vietnam,2019.0,3.776,3.371,19.8,Both sexes,75.400,NaN,NaN,NaN,...,NaN,21.2,13.4,30.6,13.900001,3.61,0.230000,25.530003,0.25,40.200005
4942,Vietnam,2019.0,3.776,3.371,19.8,Female,79.523,NaN,NaN,NaN,...,NaN,13.7,8.4,20.4,13.900001,3.61,0.230000,25.530003,0.25,40.200005
4943,Vietnam,2019.0,3.776,3.371,19.8,Male,71.301,NaN,NaN,NaN,...,NaN,29.1,18.7,40.7,13.900001,3.61,0.230000,25.530003,0.25,40.200005

,Country,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,...,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood,cost_healthy_diet_ppp_usd,annual_cost_healthy_diet_usd
0,Tunisia,2017.0,3.476,3.511,21.8,Both sexes,76.310,NaN,NaN,NaN,...,9.9,23.2,16.480000,5.420000,5.389999,0.000000,0.280000,12.289999,3.66,1335.90
1,Tunisia,2017.0,3.476,3.511,21.8,Female,78.350,NaN,NaN,NaN,...,7.9,18.5,16.480000,5.420000,5.389999,0.000000,0.280000,12.289999,3.66,1335.90
2,Tunisia,2017.0,3.476,3.511,21.8,Male,74.297,NaN,NaN,NaN,...,12.1,27.9,16.480000,5.420000,5.389999,0.000000,0.280000,12.289999,3.66,1335.90
3,Tunisia,2018.0,3.559,3.595,21.2,Both sexes,76.505,NaN,NaN,NaN,...,9.9,23.3,16.810000,5.170000,5.380000,NaN,0.270000,12.520000,3.72,1357.80
4,Tunisia,2018.0,3.559,3.595,21.2,Female,78.536,NaN,NaN,NaN,...,7.9,18.5,16.810000,5.170000,5.380000,NaN,0.270000,12.520000,3.72,1357.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4531,Uruguay,2018.0,3.170,2.830,3.0,Female,81.359,NaN,NaN,NaN,...,10.0,16.0,9.549989,26.559969,1.539998,19.139977,1.059999,10.179989,2.93,1069.45
4532,Uruguay,2018.0,3.170,2.830,3.0,Male,73.958,NaN,NaN,NaN,...,17.4,25.8,9.549989,26.559969,1.539998,19.139977,1.059999,10.179989,2.93,1069.45
4533,Uruguay,2019.0,3.254,2.905,3.3,Both sexes,77.911,NaN,NaN,NaN,...,13.0,20.4,21.059986,28.299982,1.379999,19.129988,1.079999,9.219995,3.08,1124.20
4534,Uruguay,2019.0,3.254,2.905,3.3,Female,81.478,NaN,NaN,NaN,...,9.7,15.9,21.059986,28.299982,1.379999,19.129988,1.079999,9.219995,3.08,1124.20
4535,Uruguay,2019.0,3.254,2.905,3.3,Male,74.119,NaN,NaN,NaN,...,16.6,25.2,21.059986,28.299982,1.379999,19.129988,1.079999,9.219995,3.08,1124.20

,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,Under 5 Mortality Rate,Low CI Value Under 5 Mortality Rate,...,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood,cost_healthy_diet_ppp_usd,annual_cost_healthy_diet_usd
count,4536.000000,4464.000000,4464.000000,4176.000000,4536.000000,4236.000000,4236.000000,4236.000000,4236.000000,4236.000000,...,4524.000000,4524.000000,4536.000000,4536.000000,4536.000000,4404.000000,4524.000000,4536.000000,4536.000000,4536.000000
mean,2018.002646,3.363502,3.101597,37.341810,72.459576,21.708451,16.941851,28.194155,29.193919,21.964636,...,13.184704,26.335897,20.127151,10.699245,3.243244,13.921040,1.203538,18.461953,3.189912,1164.317813
std,0.819278,0.696004,0.664551,34.863212,8.205513,21.076263,16.578540,28.175259,31.050446,23.416916,...,5.251710,11.329665,15.814231,8.582491,6.076653,15.532957,2.196015,16.201876,0.615921,224.811241
min,2017.000000,2.190000,1.955000,0.000000,49.837000,1.420000,1.070000,1.780000,1.810000,1.370000,...,3.900000,6.300000,0.400000,0.190000,0.000000,0.000000,0.000000,0.519999,2.000000,730.000000
25%,2017.000000,2.863000,2.615750,2.400000,66.400000,4.140000,3.850000,4.530000,4.860000,4.530000,...,9.300000,16.200000,6.560000,4.189942,0.549999,1.050000,0.070000,6.899999,2.770000,1011.050000
50%,2018.000000,3.275000,3.016000,23.350000,74.078000,13.450000,10.540000,16.600000,15.480000,12.330000,...,12.500000,27.100000,18.230003,7.950002,1.380464,7.469990,0.500000,14.150014,3.100000,1131.500000
75%,2019.000000,3.763000,3.463500,74.500000,78.921000,32.590000,25.550000,44.130000,44.410000,31.770000,...,15.900000,34.100000,29.549917,16.119997,3.589999,24.699997,1.380000,25.939995,3.500000,1277.500000
max,2019.000000,6.398000,6.463000,97.500000,87.669000,92.130000,81.020000,130.800000,129.300000,107.200000,...,33.100000,68.500000,76.209940,51.630010,64.329900,57.499996,16.409975,95.108190,5.650000,2062.250000

In [28]:
display(df_merge_total.head())
df_merge_final = df_merge_total.replace(np.nan, 0);
display(df_merge_final)

print(df_merge_final.isna().sum())

,Country,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,...,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood,cost_healthy_diet_ppp_usd,annual_cost_healthy_diet_usd
0,Tunisia,2017.0,3.476,3.511,21.8,Both sexes,76.310,NaN,NaN,NaN,...,9.9,23.2,16.48,5.42,5.389999,0.0,0.28,12.289999,3.66,1335.9
1,Tunisia,2017.0,3.476,3.511,21.8,Female,78.350,NaN,NaN,NaN,...,7.9,18.5,16.48,5.42,5.389999,0.0,0.28,12.289999,3.66,1335.9
2,Tunisia,2017.0,3.476,3.511,21.8,Male,74.297,NaN,NaN,NaN,...,12.1,27.9,16.48,5.42,5.389999,0.0,0.28,12.289999,3.66,1335.9
3,Tunisia,2018.0,3.559,3.595,21.2,Both sexes,76.505,NaN,NaN,NaN,...,9.9,23.3,16.81,5.17,5.380000,NaN,0.27,12.520000,3.72,1357.8
4,Tunisia,2018.0,3.559,3.595,21.2,Female,78.536,NaN,NaN,NaN,...,7.9,18.5,16.81,5.17,5.380000,NaN,0.27,12.520000,3.72,1357.8

,Country,Year,Cost of a healthy diet [CoHD],Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Gender,Life Expectancy,Infant Mortality Rate,Low CI Value Infant Mortality Rate,High CI Value Infant Mortality Rate,...,Low CI Value % Death Cardiovascular,High CI Value % Death Cardiovascular,Poultry,Beef,Sheep and goat,Pork,Other meats,Fish and seafood,cost_healthy_diet_ppp_usd,annual_cost_healthy_diet_usd
0,Tunisia,2017.0,3.476,3.511,21.8,Both sexes,76.310,0.0,0.0,0.0,...,9.9,23.2,16.480000,5.420000,5.389999,0.000000,0.280000,12.289999,3.66,1335.90
1,Tunisia,2017.0,3.476,3.511,21.8,Female,78.350,0.0,0.0,0.0,...,7.9,18.5,16.480000,5.420000,5.389999,0.000000,0.280000,12.289999,3.66,1335.90
2,Tunisia,2017.0,3.476,3.511,21.8,Male,74.297,0.0,0.0,0.0,...,12.1,27.9,16.480000,5.420000,5.389999,0.000000,0.280000,12.289999,3.66,1335.90
3,Tunisia,2018.0,3.559,3.595,21.2,Both sexes,76.505,0.0,0.0,0.0,...,9.9,23.3,16.810000,5.170000,5.380000,0.000000,0.270000,12.520000,3.72,1357.80
4,Tunisia,2018.0,3.559,3.595,21.2,Female,78.536,0.0,0.0,0.0,...,7.9,18.5,16.810000,5.170000,5.380000,0.000000,0.270000,12.520000,3.72,1357.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4531,Uruguay,2018.0,3.170,2.830,3.0,Female,81.359,0.0,0.0,0.0,...,10.0,16.0,9.549989,26.559969,1.539998,19.139977,1.059999,10.179989,2.93,1069.45
4532,Uruguay,2018.0,3.170,2.830,3.0,Male,73.958,0.0,0.0,0.0,...,17.4,25.8,9.549989,26.559969,1.539998,19.139977,1.059999,10.179989,2.93,1069.45
4533,Uruguay,2019.0,3.254,2.905,3.3,Both sexes,77.911,0.0,0.0,0.0,...,13.0,20.4,21.059986,28.299982,1.379999,19.129988,1.079999,9.219995,3.08,1124.20
4534,Uruguay,2019.0,3.254,2.905,3.3,Female,81.478,0.0,0.0,0.0,...,9.7,15.9,21.059986,28.299982,1.379999,19.129988,1.079999,9.219995,3.08,1124.20
4535,Uruguay,2019.0,3.254,2.905,3.3,Male,74.119,0.0,0.0,0.0,...,16.6,25.2,21.059986,28.299982,1.379999,19.129988,1.079999,9.219995,3.08,1124.20

Country                                                                               0
Year                                                                                  0
Cost of a healthy diet [CoHD]                                                         0
Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]    0
Percent of the population who cannot afford a healthy diet [CoHD_headcount]           0
Gender                                                                                0
Life Expectancy                                                                       0
Infant Mortality Rate                                                                 0
Low CI Value Infant Mortality Rate                                                    0
High CI Value Infant Mortality Rate                                                   0
Under 5 Mortality Rate                                                                0
Low CI Value Under 5 Mortality Rate                                                   0
High CI Value Under 5 Mortality Rate                                                  0
% Death Cardiovascular                                                                0
Low CI Value % Death Cardiovascular                                                   0
High CI Value % Death Cardiovascular                                                  0
Poultry                                                                               0
Beef                                                                                  0
Sheep and goat                                                                        0
Pork                                                                                  0
Other meats                                                                           0
Fish and seafood                                                                      0
cost_healthy_diet_ppp_usd                                                             0
annual_cost_healthy_diet_usd                                                          0
dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

#df_merge_final = df_merge_final.drop('Country', axis=1)
# df_merge_final = df_merge_final.drop('Gender', axis=1) # sa ii dai encode in viitor

X = df_merge_final.drop('Life Expectancy', axis=1)
Y = df_merge_final['Life Expectancy']

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

reg = LinearRegression().fit(X_train, Y_train)
Y_predict = reg.predict(X_test)

print(mean_squared_error(Y_test, Y_predict))
print(r2_score(Y_test, Y_predict))

display(Y_predict[0:5])
display(Y_test.head())

6.297187180289611
0.9012370478493212

array([63.5562176 , 82.45012812, 80.57204128, 80.71704294, 64.03404365])

1334    60.685
2023    83.736
4193    79.783
3062    79.971
2388    64.881
Name: Life Expectancy, dtype: float64